import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateExerciseTable1751997577208 implements MigrationInterface {
    name = 'CreateExerciseTable1751997577208'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."exercise_primarymuscle_enum" AS ENUM('Peito (Total)', 'Peito Superior', 'Peito Médio', 'Peito Inferior', 'Costas (Total)', 'Costas Superior', 'Costas Inferior', 'Dorsais (Latíssimo do Dorso)', 'Rombóides', 'Pernas (Total)', 'Quadríceps (Total)', 'Reto Femoral', 'Vasto Lateral', 'Vasto Medial', 'Vasto Intermédio', 'Posterior de Coxa (Total)', 'Bíceps Femoral', 'Semitendíneo', 'Semimembranoso', 'Panturrilhas (Total)', 'Gastrocnêmio', 'Sóleo', 'Glúteos', 'Ombros (Total)', 'Deltóide Anterior', 'Deltóide Lateral', 'Deltóide Posterior', 'Bíceps (Total)', 'Cabeça Longa do Bíceps', 'Cabeça Curta do Bíceps', 'Braquial', 'Tríceps (Total)', 'Cabeça Longa do Tríceps', 'Cabeça Medial do Tríceps', 'Cabeça Lateral do Tríceps', 'Antebraços', 'Abdominais (Total)', 'Abdominais Superiores', 'Abdominais Inferiores', 'Oblíquos', 'Trapézios')`);
        await queryRunner.query(`CREATE TYPE "public"."exercise_secondarymuscle_enum" AS ENUM('Peito (Total)', 'Peito Superior', 'Peito Médio', 'Peito Inferior', 'Costas (Total)', 'Costas Superior', 'Costas Inferior', 'Dorsais (Latíssimo do Dorso)', 'Rombóides', 'Pernas (Total)', 'Quadríceps (Total)', 'Reto Femoral', 'Vasto Lateral', 'Vasto Medial', 'Vasto Intermédio', 'Posterior de Coxa (Total)', 'Bíceps Femoral', 'Semitendíneo', 'Semimembranoso', 'Panturrilhas (Total)', 'Gastrocnêmio', 'Sóleo', 'Glúteos', 'Ombros (Total)', 'Deltóide Anterior', 'Deltóide Lateral', 'Deltóide Posterior', 'Bíceps (Total)', 'Cabeça Longa do Bíceps', 'Cabeça Curta do Bíceps', 'Braquial', 'Tríceps (Total)', 'Cabeça Longa do Tríceps', 'Cabeça Medial do Tríceps', 'Cabeça Lateral do Tríceps', 'Antebraços', 'Abdominais (Total)', 'Abdominais Superiores', 'Abdominais Inferiores', 'Oblíquos', 'Trapézios')`);
        await queryRunner.query(`CREATE TABLE "exercise" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "description" character varying, "primaryMuscle" "public"."exercise_primarymuscle_enum" NOT NULL, "secondaryMuscle" "public"."exercise_secondarymuscle_enum", CONSTRAINT "PK_a0f107e3a2ef2742c1e91d97c14" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "execution_set" DROP COLUMN "muscleGroup"`);
        await queryRunner.query(`ALTER TABLE "execution_set" ADD "RIR" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "execution_set" ADD "exerciseId" uuid`);
        await queryRunner.query(`ALTER TYPE "public"."micro_cycle_volume_musclegroup_enum" RENAME TO "micro_cycle_volume_musclegroup_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."micro_cycle_volume_musclegroup_enum" AS ENUM('Peito (Total)', 'Peito Superior', 'Peito Médio', 'Peito Inferior', 'Costas (Total)', 'Costas Superior', 'Costas Inferior', 'Dorsais (Latíssimo do Dorso)', 'Rombóides', 'Pernas (Total)', 'Quadríceps (Total)', 'Reto Femoral', 'Vasto Lateral', 'Vasto Medial', 'Vasto Intermédio', 'Posterior de Coxa (Total)', 'Bíceps Femoral', 'Semitendíneo', 'Semimembranoso', 'Panturrilhas (Total)', 'Gastrocnêmio', 'Sóleo', 'Glúteos', 'Ombros (Total)', 'Deltóide Anterior', 'Deltóide Lateral', 'Deltóide Posterior', 'Bíceps (Total)', 'Cabeça Longa do Bíceps', 'Cabeça Curta do Bíceps', 'Braquial', 'Tríceps (Total)', 'Cabeça Longa do Tríceps', 'Cabeça Medial do Tríceps', 'Cabeça Lateral do Tríceps', 'Antebraços', 'Abdominais (Total)', 'Abdominais Superiores', 'Abdominais Inferiores', 'Oblíquos', 'Trapézios')`);
        await queryRunner.query(`ALTER TABLE "micro_cycle_volume" ALTER COLUMN "muscleGroup" TYPE "public"."micro_cycle_volume_musclegroup_enum" USING "muscleGroup"::"text"::"public"."micro_cycle_volume_musclegroup_enum"`);
        await queryRunner.query(`DROP TYPE "public"."micro_cycle_volume_musclegroup_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."macro_cycle_volume_musclegroup_enum" RENAME TO "macro_cycle_volume_musclegroup_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."macro_cycle_volume_musclegroup_enum" AS ENUM('Peito (Total)', 'Peito Superior', 'Peito Médio', 'Peito Inferior', 'Costas (Total)', 'Costas Superior', 'Costas Inferior', 'Dorsais (Latíssimo do Dorso)', 'Rombóides', 'Pernas (Total)', 'Quadríceps (Total)', 'Reto Femoral', 'Vasto Lateral', 'Vasto Medial', 'Vasto Intermédio', 'Posterior de Coxa (Total)', 'Bíceps Femoral', 'Semitendíneo', 'Semimembranoso', 'Panturrilhas (Total)', 'Gastrocnêmio', 'Sóleo', 'Glúteos', 'Ombros (Total)', 'Deltóide Anterior', 'Deltóide Lateral', 'Deltóide Posterior', 'Bíceps (Total)', 'Cabeça Longa do Bíceps', 'Cabeça Curta do Bíceps', 'Braquial', 'Tríceps (Total)', 'Cabeça Longa do Tríceps', 'Cabeça Medial do Tríceps', 'Cabeça Lateral do Tríceps', 'Antebraços', 'Abdominais (Total)', 'Abdominais Superiores', 'Abdominais Inferiores', 'Oblíquos', 'Trapézios')`);
        await queryRunner.query(`ALTER TABLE "macro_cycle_volume" ALTER COLUMN "muscleGroup" TYPE "public"."macro_cycle_volume_musclegroup_enum" USING "muscleGroup"::"text"::"public"."macro_cycle_volume_musclegroup_enum"`);
        await queryRunner.query(`DROP TYPE "public"."macro_cycle_volume_musclegroup_enum_old"`);
        await queryRunner.query(`ALTER TABLE "execution_set" ADD CONSTRAINT "FK_f610ef1e5ff22a90d157f9fadfe" FOREIGN KEY ("exerciseId") REFERENCES "exercise"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "execution_set" DROP CONSTRAINT "FK_f610ef1e5ff22a90d157f9fadfe"`);
        await queryRunner.query(`CREATE TYPE "public"."macro_cycle_volume_musclegroup_enum_old" AS ENUM('CHEST_TOTAL', 'CHEST_UPPER', 'CHEST_MIDDLE', 'CHEST_LOWER', 'BACK_TOTAL', 'BACK_UPPER', 'BACK_LOWER', 'BACK_LATS', 'BACK_RHOMBOIDS', 'LEGS_TOTAL', 'QUADRICEPS', 'QUADRICEPS_RECTUS_FEMORIS', 'QUADRICEPS_VASTUS_LATERALIS', 'QUADRICEPS_VASTUS_MEDIALIS', 'QUADRICEPS_VASTUS_INTERMEDIUS', 'HAMSTRINGS', 'HAMSTRINGS_BICEPS_FEMORIS', 'HAMSTRINGS_SEMITENDINOSUS', 'HAMSTRINGS_SEMIMEMBRANOSUS', 'CALVES', 'CALVES_GASTROCNEMIUS', 'CALVES_SOLEUS', 'GLUTES', 'SHOULDERS_TOTAL', 'SHOULDERS_FRONT_DELT', 'SHOULDERS_SIDE_DELT', 'SHOULDERS_REAR_DELT', 'BICEPS_TOTAL', 'BICEPS_LONG_HEAD', 'BICEPS_SHORT_HEAD', 'BRACHIALIS', 'TRICEPS_TOTAL', 'TRICEPS_LONG_HEAD', 'TRICEPS_MEDIAL_HEAD', 'TRICEPS_LATERAL_HEAD', 'FOREARMS', 'ABS_TOTAL', 'ABS_UPPER', 'ABS_LOWER', 'ABS_OBLIQUES', 'TRAPS')`);
        await queryRunner.query(`ALTER TABLE "macro_cycle_volume" ALTER COLUMN "muscleGroup" TYPE "public"."macro_cycle_volume_musclegroup_enum_old" USING "muscleGroup"::"text"::"public"."macro_cycle_volume_musclegroup_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."macro_cycle_volume_musclegroup_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."macro_cycle_volume_musclegroup_enum_old" RENAME TO "macro_cycle_volume_musclegroup_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."micro_cycle_volume_musclegroup_enum_old" AS ENUM('CHEST_TOTAL', 'CHEST_UPPER', 'CHEST_MIDDLE', 'CHEST_LOWER', 'BACK_TOTAL', 'BACK_UPPER', 'BACK_LOWER', 'BACK_LATS', 'BACK_RHOMBOIDS', 'LEGS_TOTAL', 'QUADRICEPS', 'QUADRICEPS_RECTUS_FEMORIS', 'QUADRICEPS_VASTUS_LATERALIS', 'QUADRICEPS_VASTUS_MEDIALIS', 'QUADRICEPS_VASTUS_INTERMEDIUS', 'HAMSTRINGS', 'HAMSTRINGS_BICEPS_FEMORIS', 'HAMSTRINGS_SEMITENDINOSUS', 'HAMSTRINGS_SEMIMEMBRANOSUS', 'CALVES', 'CALVES_GASTROCNEMIUS', 'CALVES_SOLEUS', 'GLUTES', 'SHOULDERS_TOTAL', 'SHOULDERS_FRONT_DELT', 'SHOULDERS_SIDE_DELT', 'SHOULDERS_REAR_DELT', 'BICEPS_TOTAL', 'BICEPS_LONG_HEAD', 'BICEPS_SHORT_HEAD', 'BRACHIALIS', 'TRICEPS_TOTAL', 'TRICEPS_LONG_HEAD', 'TRICEPS_MEDIAL_HEAD', 'TRICEPS_LATERAL_HEAD', 'FOREARMS', 'ABS_TOTAL', 'ABS_UPPER', 'ABS_LOWER', 'ABS_OBLIQUES', 'TRAPS')`);
        await queryRunner.query(`ALTER TABLE "micro_cycle_volume" ALTER COLUMN "muscleGroup" TYPE "public"."micro_cycle_volume_musclegroup_enum_old" USING "muscleGroup"::"text"::"public"."micro_cycle_volume_musclegroup_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."micro_cycle_volume_musclegroup_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."micro_cycle_volume_musclegroup_enum_old" RENAME TO "micro_cycle_volume_musclegroup_enum"`);
        await queryRunner.query(`ALTER TABLE "execution_set" DROP COLUMN "exerciseId"`);
        await queryRunner.query(`ALTER TABLE "execution_set" DROP COLUMN "RIR"`);
        await queryRunner.query(`ALTER TABLE "execution_set" ADD "muscleGroup" character varying NOT NULL`);
        await queryRunner.query(`DROP TABLE "exercise"`);
        await queryRunner.query(`DROP TYPE "public"."exercise_secondarymuscle_enum"`);
        await queryRunner.query(`DROP TYPE "public"."exercise_primarymuscle_enum"`);
    }

}
